"""Init

Revision ID: 9906c6dd4b36
Revises: 
Create Date: 2024-01-25 11:49:46.301591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9906c6dd4b36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column("name", sa.String(), nullable=True, index=True),
    )

    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column("name", sa.String(), nullable=True, index=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
    )

    op.create_table(
        "subjects",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column("name", sa.String(), nullable=True, index=True),
        sa.Column("teacher_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="CASCADE"),
    )

    op.create_table(
        "teachers",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column("name", sa.String(), nullable=True, index=True),
    )

    op.create_table(
        "grades",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.Column("subject_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grades")
    op.drop_table("subjects")
    op.drop_table("teachers")
    op.drop_table("students")
    op.drop_table("groups")
    # ### end Alembic commands ###
